channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::pandas=2.3.3
  - conda-forge::numpy=2.3.5
  - conda-forge::biopython=1.86
  - bioconda::diamond=2.1.16
  - bioconda::pyrodigal-gv=0.3.2
  - bioconda::seqkit=2.11.0
  - conda-forge::openpyxl=3.1.5
  - conda-forge::psutil